### ISSUE TITLE
-v does not return version information

### ISSUE THREAD

**Issue by study-day** [vesoft-inc/nebula-console#107]
-v does not return version information 
log

[nebula@hadoop-node-2 ~]$ ./nebula-console-linux-amd64-v2.0.0-ga  -v
nebula-console version Git: , Build Time:
[nebula@hadoop-node-2 ~]$

**Comment by study-day** [comment]
Just upgraded to 2.0.1

**Comment by wey-gu** [comment]
@jievince it seems `gitCommit = $(shell git log --pretty=format:'%h' -1)` got empty output here or there is newline character to be handled?

**Comment by jievince** [comment]
> @jievince it seems `gitCommit = $(shell git log --pretty=format:'%h' -1)` got empty output here or there is newline character to be handled?
> 
> ```shell
> / # nebula-console -v
> nebula-console version Git: , Build Time:
> ```

It's because  I forget to add version and build info when packaging in package.yml and release.yml:
![image](https://user-images.githubusercontent.com/38901892/119291777-9dd95080-bc81-11eb-839f-6c1a3543bbf8.png)
