### ISSUE TITLE
“Where” clause is supported in “update” and “upsert” statements

### ISSUE THREAD

**Issue by forest-yuxl** [vesoft-inc/nebula-console#108]
In the current version, the "update" statement support the "when" clause.It seems the concept is not unified.We need to support the "where" clause to keep the concept consistent.

**Comment by jievince** [comment]
> In the current version, the "update" statement support the "when" clause.It seems the concept is not unified.We need to support the "where" clause to keep the concept consistent.

This is mainly for compatibility with 1.x syntax

**Comment by forest-yuxl** [comment]
this issue is moved to nebula-graph,so close it.
