### ISSUE TITLE
timeout configuration

### ISSUE THREAD

**Issue by HarrisChu** [vesoft-inc/nebula-console#129]
![image](https://user-images.githubusercontent.com/1726587/133209986-273877d5-fbb1-4b56-bfd2-6f633c5b36ea.png)

use `0` by default, if connected with a wrong ip, it would hung up forever.

![image](https://user-images.githubusercontent.com/1726587/133210180-34fd262a-38e3-4ebe-bc31-caca9153bf9f.png)

**Comment by jievince** [comment]
Users can adjust this parameter.
And I test it on my local, It doesn't hang around forever, after about ten minutes, it's over

**Comment by jievince** [comment]
It has been fixed in your PR https://github.com/vesoft-inc/nebula-go/pull/146/files
