### ISSUE TITLE
failed to verify client version: verifyClientVersion failed: wrong method name

### ISSUE THREAD

**Issue by arthasking123** [vesoft-inc/nebula-console#140]
NEBULA VERSION：2.5.1
CONSOLE VERSION： 2.6.0
OS：UBUNTU 16.04

![image](https://user-images.githubusercontent.com/16257131/139041526-cbb6a19b-bd45-40c3-baed-11530c3247f5.png)

**Comment by jievince** [comment]
You should use nebula-console of version 2.5.1
