### ISSUE TITLE
Console will send query `YIELD 1` when type query once.

### ISSUE THREAD

**Issue by Shylock-Hg** [vesoft-inc/nebula-console#148]

**Comment by jievince** [comment]
Sorry, I don't get it. Could you paste the screenshot here?

**Comment by Shylock-Hg** [comment]
e.g.
```
E1222 15:08:19.979668 82943 GraphService.cpp:161] Execute query: YIELD 1
E1222 15:08:25.319705 82943 GraphService.cpp:161] Execute query: return 'abc'

```
I just execute `return 'abc'`, but console send `YIELD 1` too.

**Comment by jievince** [comment]
> e.g.
> 
> ```
> E1222 15:08:19.979668 82943 GraphService.cpp:161] Execute query: YIELD 1
> E1222 15:08:25.319705 82943 GraphService.cpp:161] Execute query: return 'abc'
> ```
> 
> I just execute `return 'abc'`, but console send `YIELD 1` too.

When get a new connection, nebula-go will call `ping()`, which will execute `YIELD 1`. 
See https://github.com/vesoft-inc/nebula-go/blob/40030d441885c03c34054391e841e8f59443e0af/connection_pool.go#L149.
nebula-cpp also did so:
https://github.com/vesoft-inc/nebula-cpp/blob/e34071fe7bfb68e2012c94fcd03be4707216c45a/src/client/ConnectionPool.cpp#L63
```
bool Connection::isOpen() { return ping(); }


void Connection::close() {
  if (client_ != nullptr) {
    clientLoopThread_->getEventBase()->runImmediatelyOrRunInEventBaseThreadAndWait(
        [this]() { delete client_; });
    client_ = nullptr;
  }
}


bool Connection::ping() {
  auto resp = execute(0 /*Only check connection*/, "YIELD 1");
  if (resp.errorCode == ErrorCode::E_RPC_FAILURE || resp.errorCode == ErrorCode::E_DISCONNECTED) {
```

**Comment by Shylock-Hg** [comment]
I know ping, But nebula-console will send ping when user second query not just when connecting.

**Comment by jievince** [comment]
But console just uses the nebula-go's interface `session.execute`, it doesn't use  `ping`.

**Comment by jievince** [comment]
Which version of server do you use? I couldn't find this line `GraphService.cpp:161] Execute query:` in the code.

**Comment by Shylock-Hg** [comment]
> Which version of server do you use? I couldn't find this line `GraphService.cpp:161] Execute query:` in the code.

That's code I added to print the query.
