### ISSUE TITLE
there is no x86 version release for nebula-console 

### ISSUE THREAD

**Issue by bithw1** [vesoft-inc/nebula-console#172]
Hi，

I look at the https://github.com/vesoft-inc/nebula-console/releases, there are only `amd` and `arm` version, there is no `x86` version.

I would ask why there is no x86 version, thanks.

**Comment by wey-gu** [comment]
@bithw1 AMD_64 is x86_64 :)

https://en.wikipedia.org/wiki/X86-64

**Comment by bithw1** [comment]
Sure，thanks a lot helping me out，thanks a lot for the quick response!

I  am closing this issue, thanks!

**Comment by wey-gu** [comment]
Welcome, @bithw1 !
Thanks to you for raising issues, and welcome to the NebulaGraph community ;)

**Comment by bithw1** [comment]
Sure,thanks @wey-gu ,I am new and trying NebulaGraph, :-)

**Comment by wey-gu** [comment]
> Sure,thanks @wey-gu ,I am new and trying NebulaGraph, :-)

Hope you could enjoy graph-tech-playing and open-source community engagement here ;).

And btw, congrats on unlocking your very first GitHub achievement badge by closing an issue in 5 minutes :

<img width="593" alt="Screen Shot 2022-07-29 at 7 30 48 PM" src="https://user-images.githubusercontent.com/1651790/181750199-b691595f-b175-44b6-99d1-d6c364fed33d.png">
)

**Comment by bithw1** [comment]
That's interesting,:-), thanks @wey-gu
