### ISSUE TITLE
add arm64 docker build

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-console#174]
as titled.

**Comment by artemijspavlovs** [comment]
I would like to add this, it seems though that the `docker/build-push-action@v1` might only support it with the [`build_args`](https://github.com/docker/build-push-action/tree/releases/v1#build_args) property while  `docker/build-push-action@v3` supports it natively with the [`platforms` property](https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md). 

do you have anything against/are there any known implications for bumping the version of this action?

**Comment by wey-gu** [comment]
> 

Wow, thanks a lot @artemijspavlovs !

I don't think it's kept v1 for any purposes as this is just a single binary container.

We were using [v2](https://github.com/vesoft-inc/nebula/blob/master/.github/workflows/rc.yml) in NebulaGraph Core.

@jievince correct me if wrong.

Thanks again @artemijspavlovs.

**Comment by wey-gu** [comment]
Just assigned to you, please take your time and ping me for anything I could help @artemijspavlovs :)
