### ISSUE TITLE
console quit with searching “l” and enter button

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-console#191]
![image](https://user-images.githubusercontent.com/106510322/203251395-51f7f63d-fef4-4885-9153-3bb063bbbef3.png)

nebula-console version Git: b9df832, Build Time: 2022-07-18T11:31:02+0000

How To Reproduce(required)：
cmd+r  “输入l 然后回车”  

then console quit

**Comment by jievince** [comment]
Close it because it has been fixed
