### ISSUE TITLE
feat: should support when non ca being provided for TLS

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-console#237]
as titled.

**Comment by wey-gu** [comment]
```
❯ nebula-console -port 9669 -user root -p nebula -addr nebula-graph-nco9leb1ssfnlnfnb9au0.aws.dev.cloud.nebula-graph.io -ssl_insecure_skip_verify -enable_ssl
2024/04/08 14:44:02 Error: argument ssl_root_ca_path should be specified when enable_ssl is true
panic: Error: argument ssl_root_ca_path should be specified when enable_ssl is true
```

**Comment by kqzh** [comment]
> ```
> ❯ nebula-console -port 9669 -user root -p nebula -addr nebula-graph-nco9leb1ssfnlnfnb9au0.aws.dev.cloud.nebula-graph.io -ssl_insecure_skip_verify -enable_ssl
> 2024/04/08 14:44:02 Error: argument ssl_root_ca_path should be specified when enable_ssl is true
> panic: Error: argument ssl_root_ca_path should be specified when enable_ssl is true
> ```

hi wey, already supported in this pr https://github.com/vesoft-inc/nebula-console/pull/232, you can use master branch to build

**Comment by kqzh** [comment]
![image](https://github.com/vesoft-inc/nebula-console/assets/35095889/e26f6023-3fcf-49bf-8c42-9f6a7c10153e)

**Comment by wey-gu** [comment]
Sorry for this, thanks!!! @kqzh
