### ISSUE TITLE
Something wrong with the -file option

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-console#50]
As shown in the image, I imported an ngql file, created tags and edge types, but can't insert vertices.
![image](https://user-images.githubusercontent.com/69501902/99645642-6f887780-2a8a-11eb-86b4-4186be76d186.png)

The lines at the beginning are as follows.
```markdown
drop space nba;
create space nba(partition_num=10,replica_factor=1,vid_type=fixed_string(32));
use nba;
create tag player(name string,age int);
create tag team(name string);
create edge serve(start_year int,end_year int);
create edge like(likeness int);
insert vertex player(name,age) values "player100":("Tim Duncan", 42);
insert vertex player(name,age) values "player101":("Tony Parker", 36);
insert vertex player(name,age) values "player102":("LaMarcus Aldridge", 33);
insert vertex player(name,age) values "player103":("Rudy Gay", 32);
```

Please take a look. Thank you.

**Comment by randomJoe211** [comment]
If I manually `use nba` and use the same statement to insert a vertex, it works well.
![image](https://user-images.githubusercontent.com/69501902/99646426-6a77f800-2a8b-11eb-9025-509b80abc11e.png)

**Comment by jievince** [comment]
There is a time delay before graphd service knows new schema is created. So if you use -f mode, please add the local command `:sleep 3`, which means wait for 3 seconds,  between creating a schema and using schema(such as insert data). The reason why you manually do this works well is manual operation is inherently delayed

**Comment by randomJoe211** [comment]
> There is a time delay before graphd service knows new schema is created. So if you use -f mode, please add the local command `:sleep 3`, which means wait for 3 seconds, between creating a schema and using schema(such as insert data). The reason why you manually do this works well is manual operation is inherently delayed

Thank you for your reply. Could you show me how to use the command with `:sleep 3`? My original command is `./nebula-console -port <port> -u nebula -p whatever -f testspace.ngql`

**Comment by jievince** [comment]
Have a look at https://github.com/vesoft-inc/nebula-console/blob/master/data/nba.ngql.
You should add `:sleep 3` in testspace.ngql
