### ISSUE TITLE
Connecting with random account after enabling authentication shows success

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-console#57]
Console is built today.
After enabling authentication, I can still connect to Nebula Graph with a random account, but when I run any statement, a block of error message jumps out.

![image](https://user-images.githubusercontent.com/69501902/102336717-814b3500-3fcc-11eb-88e8-9d4310fb5953.png)

**Comment by jievince** [comment]
This has fixed. Thanks for your feedback
